"""add resume filename and messages table

Revision ID: e8d8c214de56
Revises: 5b1653fbda48
Create Date: 2026-09-06 21:37:08.664137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8d8c214de56'
down_revision: Union[str, None] = '5b1653fbda48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_hr_id', sa.UUID(), nullable=False),
    sa.Column('recipient_candidate_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['recipient_candidate_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['sender_hr_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_recipient_candidate_id'), 'messages', ['recipient_candidate_id'], unique=False)
    op.create_index('ix_messages_recipient_read', 'messages', ['recipient_candidate_id', 'read_at'], unique=False)
    op.create_index(op.f('ix_messages_sender_hr_id'), 'messages', ['sender_hr_id'], unique=False)
    op.add_column('candidate_profiles', sa.Column('resume_filename', sa.String(length=255), nullable=True))
    op.drop_column('candidate_profiles', 'resume_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate_profiles', sa.Column('resume_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('candidate_profiles', 'resume_filename')
    op.drop_index(op.f('ix_messages_sender_hr_id'), table_name='messages')
    op.drop_index('ix_messages_recipient_read', table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_candidate_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
